#!/usr/bin/env ruby
# -*- encoding: utf-8 -*-
$:.push File.expand_path(File.join('..','..','lib'), __FILE__)

require "rubygems"
require "bundler"
Bundler.setup

FileUtils.mkdir_p('tmp/pids') unless File.exists?('tmp/pids')

require 'with_lock'
if ARGV.include?('start')
  begin
    locker = WithLock::Client.locker
  rescue WithLock::LockException => e
    puts "Starting WithLock on #{WithLock::Server::url}!"
    WithLock::Server::start_service
    locker = WithLock::Client.locker
  end
  puts "Clearing WithLock locks!"
  locker = WithLock::Client.locker
  locker.locks.each_pair do |lock,data|
    pid = data[:owner].split('|').last
    if locker.running?(pid) || !data[:owner].include?(`hostname`.strip)
      puts "Running - pid"
    else
      puts "Not Running - pid"
      locker.release(data[:owner],lock)
    end
  end
elsif ARGV.include?('stop')
  puts "Stopping WithLock!"
  WithLock::Server::stop_service
elsif ARGV.include?('run')
  puts "Running WithLock!"
  WithLock::Server::run_service
end
